#!/usr/bin/env python3
"""Generate the XML database with 600 questions across 20 categories."""
import xml.etree.ElementTree as ET
from xml.dom import minidom

categories = [
    ("Mathematics", [
        ("What is 12 × 12?", ["144", "124", "132", "148"], "144"),
        ("What is the square root of 144?", ["12", "14", "11", "13"], "12"),
        ("Solve: 2x + 5 = 15. What is x?", ["5", "10", "7", "3"], "5"),
        ("What is 15% of 200?", ["30", "25", "35", "20"], "30"),
        ("What is the value of π (pi) approximately?", ["3.14159", "3.14169", "3.12159", "3.14000"], "3.14159"),
        ("What is 7! (7 factorial)?", ["5040", "720", "5000", "4320"], "5040"),
        ("What is the LCM of 4 and 6?", ["12", "24", "6", "8"], "12"),
        ("What is the HCF of 18 and 24?", ["6", "3", "12", "9"], "6"),
        ("What is 2^10?", ["1024", "512", "2048", "1000"], "1024"),
        ("If a triangle has angles 60°, 60°, what is the third angle?", ["60°", "90°", "45°", "30°"], "60°"),
        ("What is the area of a circle with radius 7? (π=22/7)", ["154", "144", "164", "174"], "154"),
        ("What is 3/4 + 1/4?", ["1", "4/4", "7/8", "3/8"], "1"),
        ("What is 0.75 as a fraction?", ["3/4", "1/2", "2/3", "7/8"], "3/4"),
        ("What is the perimeter of a square with side 5?", ["20", "25", "15", "10"], "20"),
        ("What is -3 × -4?", ["12", "-12", "7", "-7"], "12"),
        ("What is 1000 ÷ 25?", ["40", "50", "35", "45"], "40"),
        ("What is the mean of 2, 4, 6, 8, 10?", ["6", "5", "7", "8"], "6"),
        ("What is 5² + 12²?", ["169", "144", "196", "225"], "169"),
        ("If x = 3, what is x³?", ["27", "9", "18", "36"], "27"),
        ("What is the slope formula?", ["(y2-y1)/(x2-x1)", "(x2-x1)/(y2-y1)", "y/x", "x/y"], "(y2-y1)/(x2-x1)"),
        ("What is 45 + 55 × 2?", ["155", "200", "145", "160"], "155"),
        ("What is 1000 - 378?", ["622", "632", "612", "642"], "622"),
        ("How many sides does a hexagon have?", ["6", "5", "7", "8"], "6"),
        ("What is the Roman numeral for 50?", ["L", "X", "C", "V"], "L"),
        ("What is the next prime number after 7?", ["11", "9", "13", "10"], "11"),
        ("What is 144 ÷ 12?", ["12", "11", "13", "14"], "12"),
        ("What is the volume of a cube with side 3?", ["27", "9", "18", "6"], "27"),
        ("What is 25% of 400?", ["100", "80", "120", "75"], "100"),
        ("Simplify: 18/24", ["3/4", "2/3", "5/6", "1/2"], "3/4"),
        ("What is the median of 3, 5, 7, 9, 11?", ["7", "5", "9", "6"], "7"),
    ]),
    ("Science", [
        ("What is the chemical symbol for water?", ["H2O", "CO2", "O2", "H2"], "H2O"),
        ("What planet is closest to the Sun?", ["Mercury", "Venus", "Earth", "Mars"], "Mercury"),
        ("What is the speed of light?", ["3×10^8 m/s", "3×10^6 m/s", "3×10^10 m/s", "3×10^4 m/s"], "3×10^8 m/s"),
        ("What is the powerhouse of the cell?", ["Mitochondria", "Nucleus", "Ribosome", "Golgi body"], "Mitochondria"),
        ("How many bones are in the adult human body?", ["206", "208", "204", "210"], "206"),
        ("What gas do plants absorb during photosynthesis?", ["CO2", "O2", "N2", "H2"], "CO2"),
        ("What is Newton's first law about?", ["Inertia", "Gravity", "Motion", "Force"], "Inertia"),
        ("What is the atomic number of Carbon?", ["6", "12", "8", "14"], "6"),
        ("What is the boiling point of water?", ["100°C", "90°C", "110°C", "95°C"], "100°C"),
        ("What organ pumps blood in the human body?", ["Heart", "Liver", "Kidney", "Lungs"], "Heart"),
        ("What is the chemical symbol for Gold?", ["Au", "Ag", "Fe", "Cu"], "Au"),
        ("Which planet has rings?", ["Saturn", "Jupiter", "Neptune", "Uranus"], "Saturn"),
        ("What is the smallest unit of matter?", ["Atom", "Molecule", "Cell", "Quark"], "Atom"),
        ("What is photosynthesis?", ["Making food from sunlight", "Breathing", "Digestion", "Movement"], "Making food from sunlight"),
        ("How many chambers does the human heart have?", ["4", "2", "3", "6"], "4"),
        ("What is the nearest star to Earth?", ["Sun", "Proxima Centauri", "Sirius", "Alpha Centauri"], "Sun"),
        ("What type of animal is a whale?", ["Mammal", "Fish", "Reptile", "Amphibian"], "Mammal"),
        ("What is DNA?", ["Genetic material", "Protein", "Carbohydrate", "Lipid"], "Genetic material"),
        ("What force pulls objects to Earth?", ["Gravity", "Magnetism", "Friction", "Tension"], "Gravity"),
        ("What is the chemical symbol for Oxygen?", ["O", "O2", "Ox", "Om"], "O"),
        ("Which blood cells fight infection?", ["White blood cells", "Red blood cells", "Platelets", "Plasma"], "White blood cells"),
        ("What is the hardest natural substance?", ["Diamond", "Iron", "Granite", "Quartz"], "Diamond"),
        ("What is the unit of electric current?", ["Ampere", "Volt", "Watt", "Ohm"], "Ampere"),
        ("What is the formula for speed?", ["Distance/Time", "Time/Distance", "Mass×Velocity", "Force/Area"], "Distance/Time"),
        ("Which gas makes up most of Earth's atmosphere?", ["Nitrogen", "Oxygen", "CO2", "Hydrogen"], "Nitrogen"),
        ("What is the pH of pure water?", ["7", "0", "14", "5"], "7"),
        ("What is the process of water turning to vapor?", ["Evaporation", "Condensation", "Precipitation", "Sublimation"], "Evaporation"),
        ("What is the center of an atom called?", ["Nucleus", "Electron", "Proton", "Neutron"], "Nucleus"),
        ("What vitamin does sunlight provide?", ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B"], "Vitamin D"),
        ("What is the unit of force?", ["Newton", "Joule", "Pascal", "Watt"], "Newton"),
    ]),
    ("English", [
        ("What is a noun?", ["Name of a person/place/thing", "Action word", "Describing word", "Connecting word"], "Name of a person/place/thing"),
        ("What is the past tense of 'run'?", ["Ran", "Runned", "Running", "Runs"], "Ran"),
        ("Which of these is a synonym for 'happy'?", ["Joyful", "Sad", "Angry", "Tired"], "Joyful"),
        ("What is an antonym of 'big'?", ["Small", "Large", "Huge", "Giant"], "Small"),
        ("Which is the correct spelling?", ["Beautiful", "Beautifull", "Beutiful", "Beautful"], "Beautiful"),
        ("What is a verb?", ["Action word", "Naming word", "Describing word", "Joining word"], "Action word"),
        ("What punctuation ends a question?", ["?", ".", "!", ";"], "?"),
        ("What is the plural of 'child'?", ["Children", "Childs", "Childrens", "Child"], "Children"),
        ("Which is an adjective in: 'The red car'?", ["Red", "The", "Car", "A"], "Red"),
        ("What does 'enormous' mean?", ["Very large", "Very small", "Very fast", "Very slow"], "Very large"),
        ("What is a simile?", ["Comparison using like/as", "Exaggeration", "Giving life to objects", "Repetition of sounds"], "Comparison using like/as"),
        ("Choose the correct sentence:", ["She is going to school.", "She going school.", "She go to school.", "She goed school."], "She is going to school."),
        ("What is an adverb?", ["Modifies a verb", "Names a person", "Describes a noun", "Joins clauses"], "Modifies a verb"),
        ("What is the opposite of 'ancient'?", ["Modern", "Old", "Aged", "Historic"], "Modern"),
        ("How many vowels are in the English alphabet?", ["5", "6", "4", "7"], "5"),
        ("Which sentence is in passive voice?", ["The cat was chased by the dog.", "The dog chased the cat.", "He ate the food.", "She reads a book."], "The cat was chased by the dog."),
        ("What is a metaphor?", ["Direct comparison without like/as", "Comparison with like/as", "Sound words", "Story with moral"], "Direct comparison without like/as"),
        ("What is the superlative of 'good'?", ["Best", "Better", "Goodest", "Most good"], "Best"),
        ("Which word is a conjunction?", ["And", "Quickly", "Beautiful", "Run"], "And"),
        ("What is alliteration?", ["Repetition of initial sounds", "Rhyming words", "Opposites", "Same meaning words"], "Repetition of initial sounds"),
        ("Identify the pronoun: 'She went home.'", ["She", "Went", "Home", "The"], "She"),
        ("What is the correct article: '___ apple'?", ["An", "A", "The", "No article"], "An"),
        ("What is onomatopoeia?", ["Words that sound like their meaning", "Comparing two things", "Exaggeration", "Repetition"], "Words that sound like their meaning"),
        ("Which is a compound word?", ["Sunflower", "Running", "Beautiful", "Quickly"], "Sunflower"),
        ("What is a preposition?", ["Shows relationship between words", "Names things", "Action word", "Describes"], "Shows